name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      libsql:
        image: ghcr.io/tursodatabase/libsql-server:latest
        ports:
          - 8080:8080
        env:
          SQLD_NODE: primary

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - run: pnpm lint

      - run: pnpm test:run
        env:
          LIBSQL_URL: "http://127.0.0.1:8080"
